# Generated by Django 3.1.1 on 2020-09-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AluminumProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_code', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(default='aluminum/images/no-img.jpg', upload_to='aluminum/images/')),
                ('profile_length', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
