# Generated by Django 3.1.1 on 2020-09-05 19:19

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluminumColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=200)),
                ('preview', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
    ]
