# Generated by Django 3.1.1 on 2020-09-05 21:47

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluminum', '0002_aluminumcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extruder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extruder_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=200)),
                ('extruder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluminum.extruder')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_code', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(default='aluminum/images/no-img.jpg', upload_to='aluminum/images/')),
                ('profile_length', models.DecimalField(decimal_places=2, max_digits=3)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluminum.productsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.IntegerField(choices=[(1, 'CRUDO'), (2, 'PINTADO'), (3, 'ANODIZADO')], default=(1, 'CRUDO'))),
                ('color_name', models.CharField(max_length=200)),
                ('preview', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.DeleteModel(
            name='AluminumColor',
        ),
        migrations.DeleteModel(
            name='AluminumProfile',
        ),
    ]
