# Generated by Django 3.1.1 on 2020-09-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminum', '0003_auto_20200905_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_length',
            field=models.DecimalField(decimal_places=2, default=6.06, max_digits=3),
        ),
    ]
