# Generated by Django 3.1.1 on 2020-09-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminum', '0004_auto_20200905_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='extruder',
            name='logo_img',
            field=models.ImageField(default='aluminum/images/no-img.jpg', upload_to='aluminum/images/extruders/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='aluminum/images/no-img.jpg', upload_to='aluminum/images/profiles/'),
        ),
    ]
