# Generated by Django 3.1.1 on 2020-09-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminum', '0005_auto_20200922_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsystem',
            name='logo_img',
            field=models.ImageField(default='aluminum/images/no-img.jpg', upload_to='aluminum/images/systems/'),
        ),
    ]
