# Generated by Django 3.1.1 on 2020-09-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminum', '0006_productsystem_logo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extruder',
            name='logo_img',
            field=models.ImageField(default='aluminum/static/aluminum/images/no-img.jpg', upload_to='aluminum/static/aluminum/images/extruders/'),
        ),
        migrations.AlterField(
            model_name='productsystem',
            name='logo_img',
            field=models.ImageField(default='aluminum/static/aluminum/images/no-img.jpg', upload_to='aluminum/static/aluminum/images/systems/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='aluminum/static/aluminum/images/no-img.jpg', upload_to='aluminum/static/aluminum/images/profiles/'),
        ),
    ]
