# Generated by Django 3.1.1 on 2020-10-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminum', '0007_auto_20200927_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extruder',
            name='logo_img',
            field=models.ImageField(blank=True, default='aluminum/static/aluminum/images/no-img.jpg', upload_to='aluminum/static/aluminum/images/extruders/'),
        ),
    ]
