# Generated by Django 3.1.1 on 2020-10-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminum', '0008_auto_20201001_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsystem',
            name='logo_img',
            field=models.ImageField(blank=True, default='aluminum/static/aluminum/images/no-img.jpg', upload_to='aluminum/static/aluminum/images/systems/'),
        ),
    ]
