# Generated by Django 3.1.1 on 2020-10-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminum', '0009_auto_20201004_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsystem',
            name='logo_img',
            field=models.ImageField(blank=True, default='aluminum/static/aluminum/images/no-img.jpg', null=True, upload_to='aluminum/static/aluminum/images/systems/'),
        ),
    ]
