# Generated by Django 3.1.1 on 2020-10-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluminum', '0010_auto_20201008_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsystem',
            name='logo_img',
            field=models.ImageField(blank=True, default='aluminum/static/aluminum/images/no-img.jpg', upload_to='aluminum/static/aluminum/images/systems/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='aluminum/static/aluminum/images/no-img.jpg', upload_to='aluminum/static/aluminum/images/profiles/'),
        ),
    ]
